"""create users table

Revision ID: 14be42542965
Revises: d11f2a741aad
Create Date: 2025-09-26 00:48:03.729973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14be42542965'
down_revision: Union[str, Sequence[str], None] = 'd11f2a741aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_results', sa.Column('source_urls', sa.JSON(), nullable=True))
    op.add_column('run_results', sa.Column('num_images', sa.Integer(), nullable=True))
    op.add_column('run_results', sa.Column('num_sources', sa.Integer(), nullable=True))
    op.add_column('run_results', sa.Column('research_costs', sa.Float(), nullable=True))
    op.drop_column('run_results', 'cost_usd')
    op.drop_column('run_results', 'tokens_out')
    op.drop_column('run_results', 'retries')
    op.drop_column('run_results', 'citations')
    op.drop_column('run_results', 'tokens_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_results', sa.Column('tokens_in', sa.INTEGER(), nullable=True))
    op.add_column('run_results', sa.Column('citations', sa.TEXT(), nullable=True))
    op.add_column('run_results', sa.Column('retries', sa.INTEGER(), nullable=True))
    op.add_column('run_results', sa.Column('tokens_out', sa.INTEGER(), nullable=True))
    op.add_column('run_results', sa.Column('cost_usd', sa.FLOAT(), nullable=True))
    op.drop_column('run_results', 'research_costs')
    op.drop_column('run_results', 'num_sources')
    op.drop_column('run_results', 'num_images')
    op.drop_column('run_results', 'source_urls')
    # ### end Alembic commands ###
