"""update  table

Revision ID: cdb74d9ab3e2
Revises: dd6329196cca
Create Date: 2025-09-26 01:48:36.784034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cdb74d9ab3e2'
down_revision: Union[str, Sequence[str], None] = 'dd6329196cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_results_id'), table_name='run_results')
    op.drop_index(op.f('ix_run_results_provider'), table_name='run_results')
    op.drop_table('run_results')
    op.add_column('run_results_research', sa.Column('research_sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_results_research', 'research_sources')
    op.create_table('run_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('query', sa.TEXT(), nullable=True),
    sa.Column('report', sa.TEXT(), nullable=True),
    sa.Column('latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('errors', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source_urls', sqlite.JSON(), nullable=True),
    sa.Column('num_images', sa.INTEGER(), nullable=True),
    sa.Column('num_sources', sa.INTEGER(), nullable=True),
    sa.Column('research_costs', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_results_provider'), 'run_results', ['provider'], unique=False)
    op.create_index(op.f('ix_run_results_id'), 'run_results', ['id'], unique=False)
    # ### end Alembic commands ###
