"""create run table

Revision ID: d11f2a741aad
Revises: 035312b2fd73
Create Date: 2025-09-25 09:44:57.269582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd11f2a741aad'
down_revision: Union[str, Sequence[str], None] = '035312b2fd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_results_id'), 'run_results', ['id'], unique=False)
    op.create_index(op.f('ix_run_results_provider'), 'run_results', ['provider'], unique=False)
    op.drop_index(op.f('ix_run_id'), table_name='run')
    op.drop_index(op.f('ix_run_model'), table_name='run')
    op.drop_index(op.f('ix_run_provider'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('query', sa.VARCHAR(), nullable=True),
    sa.Column('report_text', sa.VARCHAR(), nullable=True),
    sa.Column('citations', sqlite.JSON(), nullable=True),
    sa.Column('latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('tokens_in', sa.INTEGER(), nullable=True),
    sa.Column('tokens_out', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=True),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_provider'), 'run', ['provider'], unique=False)
    op.create_index(op.f('ix_run_model'), 'run', ['model'], unique=False)
    op.create_index(op.f('ix_run_id'), 'run', ['id'], unique=False)
    op.drop_index(op.f('ix_run_results_provider'), table_name='run_results')
    op.drop_index(op.f('ix_run_results_id'), table_name='run_results')
    op.drop_table('run_results')
    # ### end Alembic commands ###
